const GET_CONTRACT = "GET_CONTRACT";
const PUBLISH_LAND = "PUBLISH_LAND";
const FETCH_LANDS = "FETCH_LANDS";
const FETCH_LAND = "FETCH_LAND";
const SELECT_LAND = "SELECT_LAND";

export { GET_CONTRACT, PUBLISH_LAND, FETCH_LANDS, FETCH_LAND, SELECT_LAND };
