const GET_CONTRACT = "GET_CONTRACT";
const PUBLISH_LAND = "PUBLISH_LAND";
const FETCH_LANDS = "FETCH_LANDS";
const SELECT_LAND = "SELECT_LAND";

export { GET_CONTRACT, PUBLISH_LAND, FETCH_LANDS, SELECT_LAND };
